### ISSUE TITLE
Can not override postgresql_packages

### ISSUE THREAD

**Issue by cornelk** [sfromm/ansible-postgresql#1]
Please consider moving vars/RedHat.yml to the defaults directory. Due to the variable precedence order of ansible it is not possible to override these values with group_vars or host_vars right now. In my case i wanted to install postgresql95 instead of postgresql. Also the path of '/usr/bin/postgresql-setup' should be configurable.

**Comment by sfromm** [comment]
Thanks for the feedback.  It looks like you are using the postgresql.org yum repository for packages?

I'll take a look at the requested changes.  Of course, patches are welcome!

**Comment by sfromm** [comment]
The first issue (variable that can be overridden) was fixed with 23bd4f3.  Still considering what to do with the second issue.

**Comment by gusto2** [comment]
Overwriting a few default role parameter will enforce installing a specific version, e.g.:

```
      postgresql_service_name: postgresql-9.6
      postgresql_data_directory: /var/lib/pgsql/9.6/data
      postgresql_pid_directory: /var/run/postgresql
      postgresql_backup_path:  /var/lib/pgsql/9.6/backups

     postgresql_packages_default:
        - postgresql96
        - postgresql96-server
        - postgresql96-contrib
        - python-psycopg2
```

however, some pgsql versions have different parameter names in the config (e.g. PostgreSQL 9.6 doesn't recognize checkpoint_segments and replication_timeout
